import React, { createContext, useContext, useState, useEffect } from 'react';

export type UILang = 'en' | 'he';

export const translations = {
  en: {
    // App
    appName: 'WordChord',
    // Nav
    myLibrary: 'My Library',
    help: 'Help',
    signOut: 'Sign Out',
    profile: 'My Profile',
    language: 'Language',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    // Song list
    newSong: 'New Song',
    import: 'Import',
    searchPlaceholder: 'Search songs by title or artist...',
    noSongsTitle: 'No songs yet',
    noSongsDesc: 'Create your first song to get started',
    createFirstSong: 'Create your first song',
    loading: 'Loading your songs...',
    songs: 'songs',
    song: 'song',
    inYourCollection: 'in your collection',
    sections: 'sections',
    section: 'section',
    justNow: 'just now',
    mAgo: 'm ago',
    hAgo: 'h ago',
    dAgo: 'd ago',
    // Dialogs / actions
    cancel: 'Cancel',
    delete: 'Delete',
    deleteForever: 'Delete forever',
    deleteSongTitle: 'Delete song?',
    deleteForeverTitle: 'Delete forever?',
    moveToDeleted: 'will be moved to Recently Deleted. You can restore it within 30 days.',
    permanentlyDeleted: 'will be permanently deleted. This cannot be undone.',
    recentlyDeleted: 'Recently Deleted',
    restore: 'Restore',
    edit: 'Edit',
    duplicate: 'Duplicate',
    share: 'Share',
    noSongsMatch: 'No songs match',
    songTitle: 'Song title',
    create: 'Create',
    creating: 'Creating...',
    deleted: 'Deleted',
    expiresIn: 'expires in',
    // Song editor toolbar
    library: 'Library',
    untitled: 'Untitled',
    view: 'View',
    songSettings: 'Song settings',
    copyToClipboard: 'Copy song to clipboard',
    displayOptions: 'Display options',
    editMode: 'Edit',
    // Settings panel
    titleLabel: 'Title',
    artistLabel: 'Artist',
    keyLabel: 'Key',
    capoLabel: 'Capo',
    transposeLabel: 'Transpose',
    exportLabel: 'Export',
    copyChordPro: 'Copy ChordPro',
    songLanguage: 'Language',
    langEnglish: 'English',
    langHebrew: 'Hebrew / עברית',
    langMixed: 'Mixed',
    // View mode controls
    chordsLabel: 'Chords',
    autoScroll: 'Auto-scroll',
    // Section editor
    labelPlaceholder: 'Label...',
    removeSectionTitle: 'Remove section',
    addLyricsBtn: 'Add lyrics',
    tapToType: 'Tap to type your song words',
    editLyrics: 'Edit lyrics',
    addSection: 'Add section',
    deleteSectionTitle: 'Delete section?',
    deleteSectionDesc: 'and all its lyrics will be removed.',
    deleteSectionFallback: 'This section and all its lyrics will be removed.',
    // Section types
    sectionVerse: 'verse',
    sectionChorus: 'chorus',
    sectionBridge: 'bridge',
    sectionIntro: 'intro',
    sectionOutro: 'outro',
    sectionCustom: 'custom',
    // How-to hint
    howToTitle: 'How to use',
    howTo1: '① Tap "Add lyrics" below and type your song',
    howTo2: '② Tap any word to pick a chord above it',
    howTo3: '③ Tap "View" to see the final result',
    chordTip: 'Tap any word in your lyrics to add a chord above it',
    // Help dialog
    helpTitle: 'Help & Tips',
    helpStep1Title: 'Create a song',
    helpStep1: 'Click "New Song", enter a title and select a language.',
    helpStep2Title: 'Add lyrics',
    helpStep2: 'Click "Add lyrics" inside any section. Type each line on a new line.',
    helpStep3Title: 'Add chords',
    helpStep3: 'Click any word in your lyrics. A chord picker will open — select a chord and press "Use [Chord]".',
    helpStep4Title: 'View & Perform',
    helpStep4: 'Toggle to "View" mode for a clean read-only display. Enable auto-scroll for hands-free performance.',
    helpStep5Title: 'Transpose',
    helpStep5: 'In song settings, use −1 / +1 to transpose all chords up or down by semitone.',
    // Chord picker
    pickAChord: 'Pick a Chord',
    currentChordsLabel: 'Current chords',
    maxChordsReached: 'Maximum 5 chords reached — remove one to add another',
    chordSearchPlaceholder: 'Search or type slash chord (C/E)...',
    recentChords: 'Recent',
    favoritesLabel: 'Favorites',
    pickRootNote: 'Pick a root note',
    noChordsFound: 'No chords found',
    // Home page
    welcomeBack: 'Welcome back',
    keepWriting: 'Keep writing!',
    totalSongs: 'Total Songs',
    withChords: 'With Chords',
    recentlyEdited: 'Recently Edited',
    viewAll: 'View all →',
    startYourNotebook: 'Start your chord notebook by creating your first song',
    // Profile modal
    profileTab: 'Profile',
    avatarTab: 'Avatar',
    passwordTab: 'Password',
    saveChanges: 'Save Changes',
    saving: 'Saving...',
    profileUpdated: 'Profile updated!',
    profileUpdateFailed: 'Failed to update profile',
    animatedAvatar: 'Animated',
    uploadPhoto: 'Upload Photo',
    imageUrl: 'Image URL',
    avatarSeedLabel: 'Design variant',
    avatarSeedPlaceholder: 'Type anything to change the look…',
    avatarSeedHint: 'Different text = different avatar look. Hit the shuffle button for a random one.',
    imageUrlPlaceholder: 'https://example.com/photo.jpg',
    imageUrlHint: 'Paste a direct link to a photo',
    previewLabel: 'Preview',
    saveAvatar: 'Save Avatar',
    avatarSaveFailed: 'Failed to save avatar',
    clickToUpload: 'Click to upload a photo',
    uploadHint: 'JPG, PNG, GIF — up to 5 MB',
    changePhoto: 'Change photo',
    currentPassword: 'Current Password',
    newPasswordLabel: 'New Password',
    minCharsHint: 'Min. 8 chars with uppercase, lowercase & number',
    updatePassword: 'Update Password',
    updating: 'Updating...',
    passwordUpdated: 'Password updated!',
    passwordUpdateFailed: 'Failed to update password',
    // Auth — Google + forgot password
    forgotPassword: 'Forgot password?',
    forgotPasswordTitle: 'Forgot your password?',
    forgotPasswordDesc: "Enter your email and we'll send you a reset link.",
    sendResetLink: 'Send Reset Link',
    sendingResetLink: 'Sending…',
    checkYourEmail: 'Check your email',
    resetEmailSent: 'We sent a password reset link to your email. It expires in 1 hour.',
    backToSignIn: 'Back to sign in',
    resetPassword: 'Reset Password',
    resetPasswordTitle: 'Choose a new password',
    resetPasswordDesc: 'Enter a new password for your account.',
    newPassword: 'New Password',
    confirmNewPassword: 'Confirm New Password',
    resettingPassword: 'Resetting…',
    invalidResetToken: 'This reset link is invalid or has expired.',
    resetLinkExpiredTitle: 'Link expired',
    resetLinkExpiredDesc: 'This password reset link is no longer valid.',
    requestNewResetLink: 'Request a new link',
    passwordResetSuccess: 'Password reset successfully',
    orContinueWith: 'or continue with',
    continueWithGoogle: 'Continue with Google',
    // Toast messages
    toastSongCreated: '"{title}" created',
    toastSongMovedToDeleted: '"{title}" moved to Recently Deleted',
    toastSongRestored: '"{title}" restored',
    toastSongPermanentlyDeleted: 'Song permanently deleted',
    toastSongDuplicated: 'Duplicated "{title}"',
    toastCopiedToClipboard: '"{title}" copied to clipboard',
    toastCopyFailed: 'Failed to copy to clipboard',
    toastUsernameEmailRequired: 'Username and email are required',
    toastSelectPhotoFirst: 'Please select a photo first',
    toastPasswordsDoNotMatch: 'Passwords do not match',
    toastPasswordMinLength: 'Password must be at least 8 characters with an uppercase letter, lowercase letter, and number',
    toastCurrentPasswordIncorrect: 'Current password is incorrect',
    signInFailed: 'Invalid email or password',
    // Auth pages
    signInToAccount: 'Sign in to your account',
    createYourAccount: 'Create your account',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    usernameLabel: 'Username',
    confirmPasswordLabel: 'Confirm password',
    signingIn: 'Signing in…',
    signIn: 'Sign In',
    creatingAccount: 'Creating account…',
    createAccountBtn: 'Create Account',
    dontHaveAccount: "Don't have an account?",
    signUpLink: 'Sign up',
    alreadyHaveAccount: 'Already have an account?',
    signInLink: 'Sign in',
    // Email confirmation
    confirmEmailTitle: 'Check your email',
    confirmEmailSent: 'We sent a confirmation link to {email}. The link expires in 3 days.',
    confirmEmailExpiredTitle: 'Link expired or invalid',
    confirmEmailExpiredDesc: 'This confirmation link is no longer valid. Please register again.',
    confirmingEmail: 'Confirming your email…',
    emailConfirmedTitle: 'Email confirmed!',
    emailConfirmedDesc: 'Your email has been confirmed. You can now sign in.',
    pendingConfirmation: 'An account with this email is pending confirmation. Please check your inbox.',
  },
  he: {
    // App
    appName: 'WordChord',
    // Nav
    myLibrary: 'הספרייה שלי',
    help: 'עזרה',
    signOut: 'התנתק',
    profile: 'הפרופיל שלי',
    language: 'שפה',
    darkMode: 'מצב כהה',
    lightMode: 'מצב בהיר',
    // Song list
    newSong: 'שיר חדש',
    import: 'ייבוא',
    searchPlaceholder: 'חפש שירים לפי שם או אמן...',
    noSongsTitle: 'אין שירים עדיין',
    noSongsDesc: 'צור את השיר הראשון שלך כדי להתחיל',
    createFirstSong: 'צור את השיר הראשון שלך',
    loading: 'טוען את השירים שלך...',
    songs: 'שירים',
    song: 'שיר',
    inYourCollection: 'באוסף שלך',
    sections: 'קטעים',
    section: 'קטע',
    justNow: 'עכשיו',
    mAgo: 'דק׳ לפני',
    hAgo: 'שע׳ לפני',
    dAgo: 'ימים לפני',
    // Dialogs / actions
    cancel: 'ביטול',
    delete: 'מחק',
    deleteForever: 'מחק לצמיתות',
    deleteSongTitle: 'מחק שיר?',
    deleteForeverTitle: 'מחק לצמיתות?',
    moveToDeleted: 'יועבר לנמחקים לאחרונה. ניתן לשחזר תוך 30 יום.',
    permanentlyDeleted: 'יימחק לצמיתות. לא ניתן לבטל פעולה זו.',
    recentlyDeleted: 'נמחק לאחרונה',
    restore: 'שחזר',
    edit: 'עריכה',
    duplicate: 'שכפל',
    share: 'שתף',
    noSongsMatch: 'לא נמצאו שירים עבור',
    songTitle: 'שם השיר',
    create: 'צור',
    creating: 'יוצר...',
    deleted: 'נמחק',
    expiresIn: 'פג תוקף בעוד',
    // Song editor toolbar
    library: 'ספרייה',
    untitled: 'ללא שם',
    view: 'תצוגה',
    songSettings: 'הגדרות שיר',
    copyToClipboard: 'העתק שיר ללוח',
    displayOptions: 'אפשרויות תצוגה',
    editMode: 'עריכה',
    // Settings panel
    titleLabel: 'כותרת',
    artistLabel: 'אמן',
    keyLabel: 'גמא',
    capoLabel: 'קאפו',
    transposeLabel: 'טרנספוזיציה',
    exportLabel: 'יצוא',
    copyChordPro: 'העתק ChordPro',
    songLanguage: 'שפה',
    langEnglish: 'English',
    langHebrew: 'Hebrew / עברית',
    langMixed: 'מעורב',
    // View mode controls
    chordsLabel: 'אקורדים',
    autoScroll: 'גלילה אוטומטית',
    // Section editor
    labelPlaceholder: 'תווית...',
    removeSectionTitle: 'הסר קטע',
    addLyricsBtn: 'הוסף מילים',
    tapToType: 'לחץ לכתוב מילות השיר',
    editLyrics: 'עריכת מילים',
    addSection: 'הוסף קטע',
    deleteSectionTitle: 'מחק קטע?',
    deleteSectionDesc: 'וכל המילים שלו יימחקו.',
    deleteSectionFallback: 'קטע זה וכל המילים שלו יימחקו.',
    // Section types
    sectionVerse: 'בית',
    sectionChorus: 'פזמון',
    sectionBridge: 'גשר',
    sectionIntro: 'פתיחה',
    sectionOutro: 'סיום',
    sectionCustom: 'מותאם',
    // How-to hint
    howToTitle: 'איך משתמשים',
    howTo1: '① לחץ על "הוסף מילים" וכתוב את השיר',
    howTo2: '② לחץ על כל מילה לבחירת אקורד מעליה',
    howTo3: '③ לחץ על "תצוגה" לתוצאה הסופית',
    chordTip: 'לחץ על כל מילה במילות השיר להוספת אקורד',
    // Help dialog
    helpTitle: 'עזרה וטיפים',
    helpStep1Title: 'יצירת שיר',
    helpStep1: 'לחץ על "שיר חדש", הכנס שם ובחר שפה.',
    helpStep2Title: 'הוספת מילים',
    helpStep2: 'לחץ על "הוסף מילים" בכל קטע. כתוב כל שורה בשורה חדשה.',
    helpStep3Title: 'הוספת אקורדים',
    helpStep3: 'לחץ על כל מילה. בוחר האקורדים ייפתח — בחר אקורד ולחץ על "השתמש".',
    helpStep4Title: 'תצוגה והופעה',
    helpStep4: 'עבור למצב "תצוגה" לתצוגה נקייה. הפעל גלילה אוטומטית.',
    helpStep5Title: 'טרנספוזיציה',
    helpStep5: 'בהגדרות השיר, השתמש ב−1 / +1 להזזת כל האקורדים חצי טון.',
    // Chord picker
    pickAChord: 'בחר אקורד',
    currentChordsLabel: 'אקורדים נוכחיים',
    maxChordsReached: 'הגעת ל-5 אקורדים — הסר אחד כדי להוסיף',
    chordSearchPlaceholder: 'חפש אקורד...',
    recentChords: 'אחרונים',
    favoritesLabel: 'מועדפים',
    pickRootNote: 'בחר שורש',
    noChordsFound: 'לא נמצאו אקורדים',
    // Home page
    welcomeBack: 'ברוך הבא',
    keepWriting: 'המשך לכתוב!',
    totalSongs: 'סה"כ שירים',
    withChords: 'עם אקורדים',
    recentlyEdited: 'נערך לאחרונה',
    viewAll: 'הצג הכל ←',
    startYourNotebook: 'התחל את פנקס האקורדים שלך על ידי יצירת השיר הראשון',
    // Profile modal
    profileTab: 'פרופיל',
    avatarTab: 'אווטאר',
    passwordTab: 'סיסמה',
    saveChanges: 'שמור שינויים',
    saving: 'שומר...',
    profileUpdated: 'הפרופיל עודכן!',
    profileUpdateFailed: 'עדכון הפרופיל נכשל',
    animatedAvatar: 'מונפש',
    uploadPhoto: 'העלה תמונה',
    imageUrl: 'קישור לתמונה',
    avatarSeedLabel: 'עיצוב',
    avatarSeedPlaceholder: 'הקלד כל דבר לשינוי המראה…',
    avatarSeedHint: 'טקסט שונה = מראה שונה. לחץ על כפתור הערבוב לעיצוב אקראי.',
    imageUrlPlaceholder: 'https://example.com/photo.jpg',
    imageUrlHint: 'הדבק קישור ישיר לתמונה',
    previewLabel: 'תצוגה מקדימה',
    saveAvatar: 'שמור אווטאר',
    avatarSaveFailed: 'שמירת האווטאר נכשלה',
    clickToUpload: 'לחץ להעלאת תמונה',
    uploadHint: 'JPG, PNG, GIF — עד 5 MB',
    changePhoto: 'שנה תמונה',
    currentPassword: 'סיסמה נוכחית',
    newPasswordLabel: 'סיסמה חדשה',
    minCharsHint: 'מינימום 8 תווים עם אות גדולה, קטנה וספרה',
    updatePassword: 'עדכן סיסמה',
    updating: 'מעדכן...',
    passwordUpdated: 'הסיסמה עודכנה!',
    passwordUpdateFailed: 'עדכון הסיסמה נכשל',
    // Auth — Google + forgot password
    forgotPassword: 'שכחת סיסמה?',
    forgotPasswordTitle: 'שכחת את הסיסמה?',
    forgotPasswordDesc: 'הכנס את האימייל שלך ונשלח לך קישור לאיפוס.',
    sendResetLink: 'שלח קישור לאיפוס',
    sendingResetLink: 'שולח...',
    checkYourEmail: 'בדוק את האימייל שלך',
    resetEmailSent: 'שלחנו קישור לאיפוס סיסמה לאימייל שלך. הקישור תקף לשעה אחת.',
    backToSignIn: 'חזרה להתחברות',
    resetPassword: 'אפס סיסמה',
    resetPasswordTitle: 'בחר סיסמה חדשה',
    resetPasswordDesc: 'הכנס סיסמה חדשה לחשבון שלך.',
    newPassword: 'סיסמה חדשה',
    confirmNewPassword: 'אמת סיסמה חדשה',
    resettingPassword: 'מאפס...',
    invalidResetToken: 'קישור האיפוס אינו תקף או שפג תוקפו.',
    resetLinkExpiredTitle: 'הקישור פג תוקף',
    resetLinkExpiredDesc: 'קישור איפוס הסיסמה אינו תקף יותר.',
    requestNewResetLink: 'בקש קישור חדש',
    passwordResetSuccess: 'הסיסמה אופסה בהצלחה',
    orContinueWith: 'או המשך עם',
    continueWithGoogle: 'המשך עם Google',
    // Toast messages
    toastSongCreated: 'השיר "{title}" נוצר',
    toastSongMovedToDeleted: '"{title}" הועבר לנמחקים לאחרונה',
    toastSongRestored: '"{title}" שוחזר',
    toastSongPermanentlyDeleted: 'השיר נמחק לצמיתות',
    toastSongDuplicated: '"{title}" שוכפל',
    toastCopiedToClipboard: '"{title}" הועתק ללוח',
    toastCopyFailed: 'ההעתקה נכשלה',
    toastUsernameEmailRequired: 'שם משתמש ואימייל הם שדות חובה',
    toastSelectPhotoFirst: 'בחר תמונה תחילה',
    toastPasswordsDoNotMatch: 'הסיסמאות אינן תואמות',
    toastPasswordMinLength: 'הסיסמה חייבת להכיל לפחות 8 תווים, אות גדולה, אות קטנה וספרה',
    toastCurrentPasswordIncorrect: 'הסיסמה הנוכחית אינה נכונה',
    signInFailed: 'אימייל או סיסמה שגויים',
    // Auth pages
    signInToAccount: 'התחבר לחשבון שלך',
    createYourAccount: 'צור חשבון חדש',
    emailLabel: 'אימייל',
    passwordLabel: 'סיסמה',
    usernameLabel: 'שם משתמש',
    confirmPasswordLabel: 'אמת סיסמה',
    signingIn: 'מתחבר...',
    signIn: 'התחבר',
    creatingAccount: 'יוצר חשבון...',
    createAccountBtn: 'צור חשבון',
    dontHaveAccount: 'אין לך חשבון?',
    signUpLink: 'הירשם',
    alreadyHaveAccount: 'כבר יש לך חשבון?',
    signInLink: 'התחבר',
    // Email confirmation
    confirmEmailTitle: 'בדוק את האימייל שלך',
    confirmEmailSent: 'שלחנו קישור אימות לכתובת {email}. הקישור תקף ל-3 ימים.',
    confirmEmailExpiredTitle: 'הקישור אינו תקף',
    confirmEmailExpiredDesc: 'קישור האימות אינו תקף יותר. אנא הירשם מחדש.',
    confirmingEmail: 'מאמת את האימייל…',
    emailConfirmedTitle: 'האימייל אומת!',
    emailConfirmedDesc: 'כתובת האימייל שלך אומתה בהצלחה. כעת תוכל להתחבר.',
    pendingConfirmation: 'חשבון עם האימייל הזה ממתין לאימות. בדוק את תיבת הדואר שלך.',
  },
} as const;

export type T = { readonly [K in keyof typeof translations.en]: string };

interface UILanguageContextValue {
  uiLang: UILang;
  setUiLang: (lang: UILang) => void;
  t: T;
}

const UILanguageContext = createContext<UILanguageContextValue>({
  uiLang: 'en',
  setUiLang: () => {},
  t: translations.en,
});

export function UILanguageProvider({ children }: { children: React.ReactNode }) {
  const [uiLang, setUiLang] = useState<UILang>(() => {
    return (localStorage.getItem('ui_lang') as UILang) || 'en';
  });

  useEffect(() => {
    document.documentElement.dir = uiLang === 'he' ? 'rtl' : 'ltr';
  }, [uiLang]);

  function handleSetLang(lang: UILang) {
    setUiLang(lang);
    localStorage.setItem('ui_lang', lang);
  }

  return (
    <UILanguageContext.Provider value={{ uiLang, setUiLang: handleSetLang, t: translations[uiLang] }}>
      {children}
    </UILanguageContext.Provider>
  );
}

export function useUILanguage() {
  return useContext(UILanguageContext);
}
